// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedDotMM.Win.Data;

#nullable disable

namespace RedDotMM.Win.Migrations
{
    [DbContext(typeof(RedDotMM_Context))]
    partial class RedDotMM_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("RedDotMM.Model.Ergebnis", b =>
                {
                    b.Property<Guid>("ErgebnisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BezahltesSchussGeld")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ErgebnisAbgeschlossen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LfdNummer")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SerienID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Zeitstempel")
                        .HasColumnType("TEXT");

                    b.HasKey("ErgebnisId");

                    b.HasIndex("SerienID");

                    b.ToTable("Ergebnisse");
                });

            modelBuilder.Entity("RedDotMM.Model.Schuetze", b =>
                {
                    b.Property<Guid>("SchuetzenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LfdNummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WettbewerbID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zusatz")
                        .HasColumnType("TEXT");

                    b.HasKey("SchuetzenId");

                    b.HasIndex("WettbewerbID");

                    b.ToTable("Schuetzen");
                });

            modelBuilder.Entity("RedDotMM.Model.Schuss", b =>
                {
                    b.Property<Guid>("SchussId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Distanz")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ErgebnisID")
                        .HasColumnType("TEXT");

                    b.Property<int>("LfdSchussNummer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Typ")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Wert")
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Zeitstempel")
                        .HasColumnType("TEXT");

                    b.HasKey("SchussId");

                    b.HasIndex("ErgebnisID");

                    b.ToTable("Schuesse");
                });

            modelBuilder.Entity("RedDotMM.Model.Serie", b =>
                {
                    b.Property<Guid>("SerienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SchuetzeID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SchussgeldBezahlt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SerieAbgeschlossen")
                        .HasColumnType("INTEGER");

                    b.HasKey("SerienId");

                    b.HasIndex("SchuetzeID");

                    b.ToTable("Serien");
                });

            modelBuilder.Entity("RedDotMM.Model.Wettbewerb", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AnzahlProbeschuss")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnzahlSerien")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnzahlWertungsSchuss")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProbeNurAufErsterScheibe")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SchussGeld")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Teilerwertung")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.ToTable("Wettbewerbe");
                });

            modelBuilder.Entity("RedDotMM.Model.Ergebnis", b =>
                {
                    b.HasOne("RedDotMM.Model.Serie", "Serie")
                        .WithMany("Ergebnisse")
                        .HasForeignKey("SerienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("RedDotMM.Model.Schuetze", b =>
                {
                    b.HasOne("RedDotMM.Model.Wettbewerb", "Wettbewerb")
                        .WithMany("Schuetzen")
                        .HasForeignKey("WettbewerbID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wettbewerb");
                });

            modelBuilder.Entity("RedDotMM.Model.Schuss", b =>
                {
                    b.HasOne("RedDotMM.Model.Ergebnis", "Ergebnis")
                        .WithMany("Schuesse")
                        .HasForeignKey("ErgebnisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ergebnis");
                });

            modelBuilder.Entity("RedDotMM.Model.Serie", b =>
                {
                    b.HasOne("RedDotMM.Model.Schuetze", "Schuetze")
                        .WithMany("Serien")
                        .HasForeignKey("SchuetzeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schuetze");
                });

            modelBuilder.Entity("RedDotMM.Model.Ergebnis", b =>
                {
                    b.Navigation("Schuesse");
                });

            modelBuilder.Entity("RedDotMM.Model.Schuetze", b =>
                {
                    b.Navigation("Serien");
                });

            modelBuilder.Entity("RedDotMM.Model.Serie", b =>
                {
                    b.Navigation("Ergebnisse");
                });

            modelBuilder.Entity("RedDotMM.Model.Wettbewerb", b =>
                {
                    b.Navigation("Schuetzen");
                });
#pragma warning restore 612, 618
        }
    }
}
